version: '3.8'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile
    command: waitress-serve --call "manage:create_app"
    expose:
      - 8080
    env_file:
      - ./.env.dev

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web